version: '2'

services:
  php:
    image: php:7.2-apache
    volumes:
      - .:/usr/src/project
      - ./app:/var/www/html
    ports:
      - "8081:80"
  phantomjs:
    image: davert/phantomjs-env
    ports:
      - "4444:4444"
