version: '2'

services:
  web:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "8080:80"
  phantomjs:
    image: davert/phantomjs-env
    ports:
      - "4444:4444"
