install_php_ext: &install_php_ext
    name: Install PHP Extensions
    command: |
        docker ps
        docker exec project_php_1 bash -c 'apt-get update'
        docker exec project_php_1 bash -c 'apt-get install -y zlib1g-dev'
        docker exec project_php_1 bash -c 'apt-get install -y libbz2-dev'
        docker exec project_php_1 bash -c 'docker-php-ext-install bz2'
        docker exec project_php_1 bash -c 'docker-php-ext-install zip'

install_composer: &install_composer
    name: Install Composer
    command: |
        docker exec project_php_1 bash -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'

version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout

      - run: sudo docker-compose up -d

      - run:
         <<: *install_php_ext

      - run:
         <<: *install_composer

      - run: docker exec project_php_1 bash -c 'cd /usr/src/project;composer install'

      - run: docker exec project_php_1 bash -c 'cd /usr/src/project;vendor/bin/codecept run'

      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
