install_php: &install_php
    name: Install PHP
    command: |
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install php7.2 php7.2-cli php7.2-json php7.2-readline php7.2-mbstring php7.2-bz2 php7.2-dom php7.2-curl

install_composer: &install_composer
    name: Install Composer
    command: |
        ls -al
        curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout

      - run:
         <<: *install_php

      - run:
         <<: *install_composer

      - run: composer install

      - run: sudo docker-compose up -d

      - run: vendor/bin/codecept run
